SauravMukherjee44/Aec-Library-Website

- assets/css/style.css
- index.html
1. Shadow effect added in the navigation bar
2. New font added (poriet-one)
3. Navigation bar and footer background color changed
4. Small transition-effect
> Changes made in Style-sheet:

- assets/css/style.css
- index.html
navbar color change according to footer and name also added
> navbar issues solved

- assets/css/style.css
> Spacing issue solved

- assets/css/style.css
> Padding changed

- assets/css/donate-book.css
> ui modifications in donate-book

- README.md
- assets/css/style.css
1) Changed main body form's alignments.
2) Scaled down the submit buttons.
3) Added margin below the Linkedin and GitHub buttons.
https://sushantpatial.github.io/Aec-Library-Website/
> Fixed some alignment issues

- assets/css/style.css
- index.html
refactor the **index page inline CSS** of the body tag to **external** style sheet
it helps a website to load faster than previous
> refactor the inline CSS of index page

- CONTRIBUTING.md
Fix #17 
Update and add few steps for better understanding and a clear picture for the contributors.
> Contribution Guidelines.

- assets/css/donate-book.css
- assets/css/style.css
- index.html
- public/donate-book.html
I edit input type in filling form and edit background image. A bug in choose 'state' that I add state name.
> major changes in Donate Books section

- assets/js/script.js
> add book fixes

- assets/css/style.css
- index.html
Reverts SauravMukherjee44/Aec-Library-Website#41
> Revert "Input CSS form updated"

- assets/css/style.css
Reverts SauravMukherjee44/Aec-Library-Website#53
> Revert "Preloading screen adjusted to full screen"

- assets/css/donate-book.css
ERROR IN RESPONSIVE VIEW OF DONATE BOOK WEBPAGE :
------------------------------------------------------------------------------------------------------------------------------------------
FIXED RESPONSIVE VIEW :
> Responsive changes in donate books page

- assets/css/style.css
- index.html
- resource.css
- resource.html
Do check:
https://ankitapal12.github.io/Aec-Library-Website/
> Fixed some bugs and made some changes in resources page

- assets/css/donate-book.css
> Aligned checkbox in a straight line

- assets/css/style.css
- index.html
Created a dropdown list for the authors' field adding the names of some famous authors.
> Added authors dropdown list with names of a few popular authors

- README.md
> Added open in vsc element to readme #65

- assets/css/style.css
- index.html
Added some CSS and changed the font of the website to make the website look a little bit more professional.
> Made some UI changes using CSS

- assets/css/style.css
- index.html
Reverts SauravMukherjee44/Aec-Library-Website#79
> Revert "Made some UI changes using CSS"

- assets/js/script.js
- index.html
Found mismatched id values...updating this fixes the add book button
> Fixes #88 - Add Book Button

- resource.css
- resource.html
HI I just made the navbar responsive and fixed the issue
>  made navbar items responvie

- assets/css/style.css
> Made all input fields uniform

- assets/css/style.css
- index.html
A new style added for with search icon on button
> button style added with icon

- assets/css/style.css
- index.html
Reverts SauravMukherjee44/Aec-Library-Website#71
> Revert "button style added with icon"

- resource.css
- resource.html
Fixes #113 
* I've added responsiveness and styling
* Also made a couple of changes in the alignment and spacing.
* Added slight hover effects to the images
> Added changes to Study Materials Section

- resource.css
- resource.html
Added Title bar icon on the resource page . Hover animation on the navbar in resource page now available.
> Added Title Bar icon and hover animation on navbar in resource page

- public/donate-book.html
Added autofocus in name so it automatically blink cursor on name section .
> added autofocus in donation form(/donate-book.html) in name section

- resource.css
- resource.html
I added animated heading to resource page.If you like then please accept my PR i'm a beginner and i'm doing it for Hacktoberfest 2021
> added animated heading to resource page

- resource.css
- resource.html
Reverts SauravMukherjee44/Aec-Library-Website#120
> Revert "added animated heading to resource page"

- public/donate-book.html
Added more labels like 
- country 
- Landmark,
- Alternate Phone 
in the donation-form to ease the donation process .
**Those who can't come to college for donating the book , more information in the form will help reaching out to them easily.**
> Added More Labels

- assets/css/contact us.css
- public/contact us .html
- resource.html
> Added Contact us

- assets/css/style.css
> Added Hover Effect on links

- assets/css/terms.css
- public/donate-book.html
- public/terms&conditions.html
Note: I have kept the page style inline in book-donation.css, main idea was to include terms and conditions for donating books, as one cannot agree without reading them :D
> Added : Terms and Conditions for book donation.

- README.md
Added contributing guidelines in the README file. I have written this in such a way that it can help any newbie to contribute to this project without any problem. Please merge this and label it with suitable labels.
> [added] Contributing Guidelines

- index.html
Authors dropdown list added with an 'Others' option and a field next to dropdown list created
> Authors dropdown list added with an 'Others' option

- index.html
I have added the contact us section in the footer. Please link relevant contact details wherever needed.
> contact us in the footer added

- index.html
https://sangeeta874.github.io/Aec-Library-Website/
> Added the contact us at footer of index

- index.html
Reverts SauravMukherjee44/Aec-Library-Website#142
> Revert "contact us in the footer added"

- README.md
Added Bootstrap in tech Stack and removed unnecessarily  brackets
Previously :
After :
> Update Tech Stack in README.md

- assets/js/script.js
- index.html
issue resloved -->
window.onload function has issue of Cannot read properties of null (reading 'style') (script.js:165)
> window.onload issue resolved

- assets/css/style.css
I changed the the size of text and made the text align :center  ,even I changed the size of git and linkedin icon.
> Change the alignment and Text Size of elements on the footer #152 /issues no. 152

- assets/css/style.css
#150 fixed the spacing issue between nav items,
> added margin between nav items

- assets/css/contact us.css
- public/contact us .html
https://sangeeta874.github.io/Aec-Library-Website/
> Added the header and footer in contact us page 

- assets/css/style.css
- assets/js/script.js
- index.html
Reverts SauravMukherjee44/Aec-Library-Website#114
> Revert "Make the website responsive for mobile phone 🐱‍🏍 #35 /issue35"

- assets/js/script.js
- index.html
Adds the search functionality to the search button. It filters the books comparing the book's name or the author's name with the saerch term. It can search with one or more terms and the search function searches separatedly. Suggestions or code optimizations are welcome! 😀😀😀
Solves #151 
Link for testing => https://xaconi.github.io/Aec-Library-Website/
Add some books to the table and try to search them with the header search box.
> Add search function to search button

- assets/css/style.css
Fix the alignment of items on the Navbar. Increase Spaces #150
> Space issue fixed  #150

- assets/css/donate-book.css
Changed the margin so that heading can be visible
> fixed header not visible issue

- assets/css/style.css
- index.html
Fixed the nav alignment issue and if any more changes is required please let me know.please review my PR #150 @SauravMukherjee44
> fix the alignment of navbar and made it responsive

- assets/css/donate-book.css
- public/contact us .html
- public/donate-book.html
https://sangeeta874.github.io/Aec-Library-Website/
> Added the header and footer in Donate book page

- assets/css/style.css
- index.html
Reverts SauravMukherjee44/Aec-Library-Website#180
> Revert "fix the alignment of navbar and made it responsive"

- resource.css
- resource.html
There were a lot of missing tags and linting errors, I have fixed them here.
Fixes #186.
> Fixed linting in resources HTML.

- assets/css/donate-book.css
- assets/css/style.css
https://sangeeta874.github.io/Aec-Library-Website/
> Fixed the nav bar and donate form

- assets/css/style.css
changed the position, font and made it more responsive and flexible for user to use it .
> Navbar issue fixed

- assets/css/style.css
Reverts SauravMukherjee44/Aec-Library-Website#198
> Revert "Navbar issue fixed"

- resource.css
- resource.html
> footer updated

- public/contact us .html
- public/donate-book.html
> Fixed Navbar

- assets/css/style.css
- assets/js/script.js
- index.html
@SauravMukherjee44  review the PR #74 . Resolved all the conflicts.
> fetch upstream done and conflicts resolved

- resource.html
Update:-linked contact section
> Shivamaddition

- assets/css/style.css
- index.html
**Changes made**
- Added a new background gradient to the column
- Made minor font changes and more to suite the look
**Reason for change**
- To provide the column a compact and clean look
- To make the text inside more legible, because the it was hard to read previously because of the background image
> Resigned the "Your Books" column

- public/terms&conditions.html
improved terms&conditions page to match the theme and worked on padding.
> Modified terms&conditions.html

- Login_page/login_page.html
- Login_page/login_style.css
The unnecessary scroll bar is removed from the login page also the UI of the input fields is now improved.
ISSUE : #212
> Un-necessary scroll bar is removed.

- about.html
Fixes #206 Added content to about page
> Add Content to the About Page

- assets/css/style.css
> fixed home navbar

- assets/css/style.css
make changes in the input field now it is giving better look and also align heading to the center.
issue no -#235
> Changes in input field (issue no - #235)

- assets/css/style.css
Reverts SauravMukherjee44/Aec-Library-Website#250
> Revert "Changes in input field (issue no - #235)"

- assets/css/style.css
- assets/js/script.js
- index.html
Reverts SauravMukherjee44/Aec-Library-Website#254
> Revert "Updated resources table in the home page"

- about.html
- public/donate-book.html
I have fixed some bugs in navigation bar related to href of anchor tag
> hrefBugFixed

- public/donate-book.html
> resolve conflict : Added missing about page link to navigation bar of donate-book.html #256

- about.html
- assets/css/About.css
- assets/css/style.css
- public/donate-book.html
Changes 
- make about page responsive 
- fixed navbar and footer
> Fixed About page

- assets/css/style.css
- Changed font of nav bar.
- Aligned navbar properly
> Highlighted nav bar . Please marge this.

- assets/css/style.css
Reverts SauravMukherjee44/Aec-Library-Website#270
> Revert "Highlighted nav bar . Please marge this."

- Login_page/login_style.css
- index.html
- public/donate-book.html
[x] Pointing type in Login Page -> Set to cursor of ghost(inactive session) buttons
[x] Linked index.html to login_page ->changed href
[x] Improved readability 
Thank you!!!
> Pointing type(Login_Page) && Minor fixes

- index.html
> blog card added

- index.html
> Added new blog description.

- sign up page/index.html
> Added password visibility

- resource.html
> Updated Youtube link

- resource.html
> Updated another Youtube link

- assets/css/style.css
Added hover effects to nav bar and login button.
https://user-images.githubusercontent.com/79199262/146344827-13597cfd-4fdc-4937-a208-7424acc35287.mp4
> added hover effects

- assets/js/script.js
- index.html
I fixed the edit button so that it allows the user to edit the already added books. I implemented the edit feature.
> Fixed the edit feature #494

- resource.html
Added tutorials in resources page.
> added resources

- assets/css/contributors.css
profile button added on contributors page
> Created button on Contributors page

- assets/css/contact us.css
- public/contact us .html
> Added more social icons in footer of contact us page

- index.html
Added 4 more questions and answers to the FAQ section.
> Modified FAQ section

- about.html
- public/donate-book.html
Fixed bug #551 remove Search Field
> #551 remove Search Field

- resource.css
- resource.html
> I edited resource.html file and added technical courses, as per the issue #545

- assets/css/style.css
> Updated UI of FAQ

- index.html
I have successfully resolved the issue and have added both the **TITLE and DESCRIPTION** in the BLOG section of the Website.
**ISSUE NUMBER - #561**
Please merge my PR !! @SauravMukherjee44
> added the Title and Description to BLOGS

- resource.html
> Add new features to the Library According your Ideas. #562

- Quiz/css/game.css
- Quiz/css/style.css
- Quiz/pages/game.html
Resolves #579 
- Made the quiz section in `index.html` responsive.
- Made the quiz page responsive also. 
Mobile view of Quiz page -
Tablet view of Quiz page -
Mobile view of quiz section in `index.html` -
Tablet view of quiz section in `index.html` -
> Quiz section made responsive

- Quiz/css/highscore.css
- Quiz/css/style.css
- Quiz/js/end.js
- Quiz/js/highscore.js
- Quiz/pages/end.html
- Quiz/pages/highscore.html
- index.html
Closes #587 
- Added a high score viewing page
- Designed for the same
- After completing the quiz the user will be asked to enter his/her name
High score button in `index.html` ( Home page ) -
Asking a user to enter his/her name after completing the quiz  -
Highscore page -
> Highscore feature in quiz section added

- assets/css/donate-book.css
- public/donate-book.html
Issue #589 
I have improved the UI of donate books page. It is responsive.
> Improved UI of Donate books page

- resource.css
- resource.html
I have added a volume controller in the audio book section of the resource page
Before:
After:
> Added a volume controller in the audio book section of the resource page

- assets/css/style.css
- index.html
Closes #582
UI Enhancement of book issue section.<br>
> Book Issue Section

- index.html
@SauravMukherjee44 merge this prissue #530  done
> New pr  implement the uses of search button

- assets/css/style.css
- index.html
I have modified feedback section
> Modified Feedback Section

- assets/css/style.css
> Fixed speech to text icon and scroll to top btn overlap

- index.html
@SauravMukherjee44 .
I have again added the button. Kindly check
> Quiz Highscore button added

- index.html
> Create a Newsletter Service for the Website #525

- index.html
- When the user clicks on the submit button for a newsletter it should show the submitted message!
- Make both fields are required.
> Feature: Add a alert message in newsletter #614

- assets/css/contributors.css
- contributors.html
I have improved the UI of the footer section of the contributors page and added remaining contributors
> Improved the UI of the footer section of the contributors page and added remaining contributors 

- index.html
> Solved #610 no issue

- assets/css/style.css
- index.html
Solves #613 
- Added validation of feedback form with pop-up msg
Video 
https://user-images.githubusercontent.com/78646418/154809877-3709a948-e817-4b77-b813-117f08fb181a.mp4
> Pop up msg added

- blogs.css
- blogs.html
- index.html
> Create a Blogs page and Link it to the Home Page 🧑‍💻 #563

- assets/css/style.css
- index.html
#622 
I have done the required changes and here is what the site looks like now.
> Improved issue book section

- public/donate-book.html
- Country changed to State
- State changed to City
I'm a GSSoC'22 contributor. I've made the required changes. Kindly merge it to main.
> Changed the Book Donation Form Option values

- index.html
> Add questions in FAQs section

- assets/css/style.css
- index.html
- Fixed the padding of the form input fields
- Added animations and smooth transitions to the  input fields and their labels 
- Fixed the improper animation of the submit button
- Made the form and the image associated with it mobile responsive
- Added animations to the container holding the form
The images of the changed form are:
This fixes the issue number #634.
Thank you.
> Improved the contact form UI and made it mobile responsive for issue number #634

- assets/css/style.css
- index.html
🛠️ Fixes Issue
Example: Closes issue #651 
👨‍💻 Changes proposed
updated newsletter form with better CSS and added icons for the placeholders.
📷 Screenshots
> updating newsletter form

- assets/css/style.css
- index.html
- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.
> Make changes to blog section of look them more elegant

- assets/css/style.css
- index.html
> Button Modification

- index.html
- Updated the Web Development Blog link
I'm a GSSoC'22 contributor. I have fixed the issue. Kindly merge it to main.
> Fixed Web Development Read More Button

- index.html
Closes #626
Fixed dropdown Specify Author is an unselectable option and it has a check
I have fixed the issue. Please merge it.
> fixed issue 626-Specify author dropdown

- resource.css
- resource.html
Feature: Made a Navigate-To/Back-To Top Button on Resources Page
I'm a GSSoC'22 contributor. I have added the proposed feature. Kindly merge it to main branch.
> Fixed issue #653 : Navigate to Top Button Added : GSSoC22

- about.html
- assets/css/About.css
Closes #661 
changes layout of quick links of about page and change in color to make it more attractive .
- My code follows the code style of this project.
- This PR does not contain plagiarized content.
-  The title of my pull request is a short description of the requested changes.
> Issue-661 resolved

- resource.css
- resource.html
Closes #662 
Validation of feedback form of resource page done.
- My code follows the code style of this project.
-  This PR does not contain plagiarized content.
-  The title of my pull request is a short description of the requested changes.
> Issue-662 resolved

- resource.css
This is how it was looking-
**(Before)**
This is how it was looking-
**(After)**
> Modified the UI (Basically focused on font) of Resources Page.

- index.html
Closes #678 
Added links to **Our Story** and **Accessibility**
**Our Story**
**Accessibility**
> Fixed the bug

- resource.css
- resource.html
worked on volume button. 
social media icon was not visible which is in footer now its visible.
- [👍🏻  ] My code follows the code style of this project.
- [👍🏻  ] This PR does not contain plagiarized content.
- [👍🏻  ] The title of my pull request is a short description of the requested changes.
Before : 
https://user-images.githubusercontent.com/62801180/156769278-3e88fea8-7830-4004-b9db-dd36ca9f01bd.mp4
after : 
https://user-images.githubusercontent.com/62801180/156769334-deb6f34e-c8b9-4f06-b855-8c58500185c4.mp4
> worked on volume button and social media icon which is in footer

- .vscode/settings.json
- assets/css/donate-book.css
- public/donate-book.html
Resolved #687 
Improvement of User Interface of Donate Books page
NA
> UI Improvement Donate Book Page

- resource.css
- resource.html
Closes #704  
- In /resources footer was not proper, I've styles the social icons, added some padding around
- Added padding around Middle box, Left box, and Right box, which was improper
- Because of top button at footer, content was not visible properly, I had fixed it
- [Y] My code follows the code style of this project.
- [Y] This PR does not contain plagiarized content.
- [Y] The title of my pull request is a short description of the requested changes.
Now, it's perfect :)
> Improvements in footer

- index.html
closes-#693
Category option in category dropdown is an unselectable option i.e. only for reference.
> issue-#693 Fixed category dropdown

- Contributors.md
- Forgot_Password/index.html
- Forgot_Password/recovery.html
- Login_page/login_page.html
- index.html
- resource.html
Closes #671 
Making the logo at the main page, login page, Recovery page, Forget password page and resource page
> Fixing all logo links to the main page of the website

- contributors.html
Changes Made in Footer Section of Contributors Page
-  "Donate Books" linked to its working url (previously linked to wrong url).
-  "Privacy Policy" linked to index page (previously linked to broken url).
> #719 fixed footer section in contributors page

- assets/css/audiobook.css
- assets/js/audiobook.js
- index.html
> Add features in Listen to Audiobooks section 

- Login_page/login_style.css
- sign up page/index.html
- sign up page/style.css
Closes #738 
Closes #739 
I've added bottom margin to the sign in button
- [Y] My code follows the code style of this project.
- [Y] This PR does not contain plagiarized content.
- [Y] The title of my pull request is a short description of the requested changes.
> Modified Sign In Button

- assets/css/style.css
- index.html
- resource.css
Fix issue #740 
Please merge my PR if it looks better.
> Added linear-gradient in footer

- about.html
- assets/css/About.css
Example: Closes #757 
- Made image responsive
- Added spacing between image and terms and condition text
- Increased size of social icons
- Center aligned quick links footer bar 
Have made changes to footer and image mainly
Before changes
After changes
> Made spacing fixes in about us page

- resource.css
#763 Issue I added the hover effect in  NCERT Books  in Resources page.
> Hover effect NCERT Books

- Quiz/js/game.js
closes #732 
game.js is modified to fix the bug
> quiz section fixed

- assets/css/donate-book.css
- public/donate-book.html
Fixed Issue 775
Added a reset button to donation form so that new entries can be made quickly by clearing previously entered data. This reset button is convenient to use and ensures a user friendly interface.
> added reset button to donation form. Issue #775

- Quiz/js/game.js
Closes #674 
1)Added a html entity decoder function in game.js which decodes HTML Entities which accepts a string and return its HTML equivalent text.
2) Called the entity decoder and assigned its return value in map for questions and choices.
> Added HTML Entity Decoder in game.js

- blogs.css
- blogs.html
Closes: #776 
- Created a dynamic grid which is responsive without the use of any media queries
- Made card and image sizes equal
- Removed unnecessary space between heading and text
- Changed heading colour from red to green
- Replaced button with text link for simplicity
CSS Grid was used to completely redesign the blog layout.
Before changes
After changes
Testing responsiveness after changes
> Created dynamic grid for blog section

- assets/css/contributors.css
- contributors.html
- index.html
#767 
change in index.html file 
✔ My code follows the code style of this project.
✔This PR does not contain plagiarized content.
✔ The title of my pull request is a short description of the requested changes.
----Before 
----After
> added missing Opening h1 and div tag

- index.html
Closes #773 
1. Created an "id" for faq section.
2. FAQ Anchor link in footer is targeted to that Id.
> #773 fixed FAQ in Homepage

- index.html
- recommended_books.js
- recommended_books.json
#792 #794 
added meta tags to index.html
added icon to index.html
removed recommended books section
created json file with these books data
created js file to fetch the file and build this section
> issues #792 and #794, SEO, icon, JSON

- assets/css/privacy-policy.css
- public/privacy-policy.html
Closes #780 
1. Created a new Privacy Policy Page.
2. Added Privacy Policy content.
> 780-created-privacy-policy-page

- resource.css
- resource.html
#809 
-  Added Navigation tabs for NCERT Books and Audio Books in resources page.
-  Removed the home tab from book list navigation and added a separate icon of it.
> Added missing navigation links in resources page.

- public/donate-book.html
> changes made #769

- index.html
Closes: #828 
-Horizontal scrolling bug was fixed
> Horizontal scrolling bug fixed

- assets/css/style.css
i have aligned items center in mobile view.....
now it's looking good
> aligned items center in mobile view

- about.html
- assets/css/About.css
Closes #858  
Fixed some quick links which didn't function properly and made some CSS changes.
> fixed broken links and css change

- blogs.css
- blogs.html
Updated blog page UI and Added more blogs.
#859 
1)I added 6 more blogs in the blog section with relevant topics ,images and links added to read particular blog.
2)Made the blog button active on blog page in nav-bar. (Earlier it was About page)
3)After hovering on particular blog and also on image there is some Y-transform, box shadow effect , color change (of text both heading and para)
4)Read More button is made attractive. And after hovering color ,border changes.
I made all the required changes and PR .Please review my changes. Thanks in advance!
> BlogSection Updated

- resource.html
Closes #873 
1) The improper link has be changed to the proper link.
> Linked images of Web development Course properly

- blogs.css
- blogs.html
#876 
Increase in size of the card in blog page to adjust the "read more" button.
Read more button was not inside the card in blog page. This PR increases the height of the card and adjusts the "Read More" button in the card which now looks good.
Even in small screen , That button looks good.
> Read More Button (blog page) Placement in Card fixed.

- assets/css/style.css
- index.html
- style.css
> The width of the main website was changed

- assets/css/style.css
- index.html
- style.css
Reverts SauravMukherjee44/Aec-Library-Website#866
> Revert "The width of the main website was changed"

- assets/css/style.css
Closes #879 
changes in style.css done which include:
1. changed margin
2. align-items, justify-content
3. width of the card
Before:
After:
> Fixed styling for choose and read books section card in mobile view

- Contributors.md
- assets/css/style.css
- Changed the hover effect in navbar section.
- Applied transition effect in Choose and Read Books.
- Modified Issues here section.
I have made all the changes as I had requested in my issue.
These are all the changes I made in the project ->
1.) Changed the hover effect on icons in navbar section. See the below screenshots for a better understanding.
- Before ->
- After ->
3.) Modified "Issue here" div as some of the elements were hiding in medium and small width devices. Here are the screenshots ->
- Before
- After
2.) Added transition effect in "Choose and Read Books" div.
Please review my changes and merge my pull request so that user experience is improved. Thank you!
> Made changes to navbar, issue and choose and read books

- sign-up-page/index.html
- sign-up-page/style.css
…r and added some hover effects
The buttons were not looking good and there was no such CSS there. I have added all the styles and now it's looking cool.
- I have added new CSS in the html page
- I have added cool animations and effects in the website.
- [ ✔️ ] My code follows the code style of this project.
- [ ✔️ ] This PR does not contain plagiarized content.
- [ ✔️ ] The title of my pull request is a short description of the requested changes.
> change sign-up.html page add some CSS and made the buttons much better

- blogs.html
> some more technical blogs added

- contributors.html
Fixed the links and added Terms and Conditions text and link in Footer of Contribution page
- Added Terms and Conditions Text and link in the Footer of Contributions page
- Corrected all the links of Contributions page footer section 
- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.
This project is really Awsome. I can't imagine how much dedication you must have putted into this amazing project.
Added Text and Link
Corrected all the links as you can see it's broken
> Fixed links and Added Terms and Conditions in Footer of Contributions page

- Forgot_Password/index.html
- Forgot_Password/recovery.html
- Login_page/login_page.html
> updated all the footer youtube links with a new hyperlink with your name

- about.html
- assets/css/About.css
- assets/css/donate-book.css
Signed-off-by: Rahul Kumar <rkgkumar072@gmail.com>
Closes #888 
Now
Nav of donate book page
> Changes about page footer: enhanced visibility & donate book page nav color

- assets/js/Donate_Book.js
Added more city options for Karnataka.
> Added more important cities in Karnataka

- Login_page/login.js
- Quiz/js/game.js
- assets/css/audiobook.css
- assets/css/style.css
- assets/js/audiobook.js
- assets/js/script.js
- index.html
- recommended_books.js
- sign-up-page/index.js
Fixes #878
1. Fixed browser console errors
2. Removed console logs
Before:
After:
> Bug Report: Fix Browser Console Errors

- Login_page/login.js
- Login_page/login_page.html
- Login_page/style.css
- sign-up-page/index.html
Modified Login page UI to make it relative to the Sign Up page
Old Login Page:
Modified Login Page:
Sign Up Page for comparison:
> Login Page UI Modified

- assets/css/style.css
- index.html
Added hover feature for the subscribe button in the newsletter section which enhances the user experience.
Button size:
When cursor is brought over to the button
> Hover feature to Subscribe button

- resource.html
Closes Issue #910 
The GitHub Icon is added instead of the Text
> The GitHub Icon is now added in place of text

- index.html
Closes #928 
Hey @SauravMukherjee44  I have made appropriate changes to the links  and now it goes to proper Python Docs, please review it.
> Modified links properly

- index.html
> Fixed Navbar links and Read books section.

- public/donate-book.html
Added TextArea in Address : 
Hey @SauravMukherjee44  I made the appropriate changes , please review it .
> Added Textarea in Address

- blogs.html
- Changed Bootstrap version from 4.3 to 5.1
- Added scripts to the end of the body tag for faster loading and improved performance
> Navbar toggle bug in blogs.html

- assets/css/style.css
Closes #1004 
Changed the transparency from 0.25 to 0.75
Changed color of the title
> Improve Visibility Of GetInTouch

- index.html
Fixes issue #1003 
Grammatical error fixed
- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.
> grammatical error fixed

- Quiz/css/highscore.css
- Quiz/css/style.css
- index.html
#995 
1. Changed the UI of the high score section a little.
2. Made the High score section responsive for all devices.
> Updated High-score Section.

- resource.html
Signed-off-by: Rahul Kumar <rkgkumar072@gmail.com>
#954 
- Broken images resolved
- Added new courses
> Added programming lang. courses and resolved broken images

- about.html
- blogs.html
- cbse_notes.html
- contributors.html
- index.html
- ncert.html
- resource.html
Closes #947 
Changed the year in footer using javascript to keep it dynamic
> added footer year using javascript

- assets/css/style.css
Closes #966 
Hey @SauravMukherjee44  I made the necessary changes ,please have a look.
Previously:
Now:
> Modified 'Yours Books' Section correctly.

- index.html
* Corrected the 2 spelling mistakes which were present in the FAQ's section.
Before:
After:
Hey @SauravMukherjee44 @IAmTamal please review my PR
> Changes made

- assets/css/style.css
#1028
shifting borders of html class "hero-right" from basic rectangular ones to curved ones. Which is enhancing the UI.
Borders of list contents have been changed to curved ones from basic rectangular ones
UI is looking nice with small change
before
after
> Adding curve to borders, enhancing UI

- assets/css/style.css
#1031 
Found code-base-bug of unclosed bracket of media queries
now FIXED
closing media query using closing bracket
> [Bug-in code-fixed]closing unclosed bracket in css file #1031

- resource.html
* Updated the instagram link in the resources page so that when we click on the instagram icon, it will redirect to the founder @SauravMukherjee44's official instagram id.
> Updated the instagram link in the resources page

- blogs.html
<Closes #1067  -->
New blogs on Blockchain added.
> Blogs added

- recommended_books.js
> Fixes #1053 
- New String Variable to hold all the HTML syntax  to add recommended books (booksList)
- Using `recommended_books.innerHTML` outside the loop.
> Fixed #1053

- Login_page/login_page.html
I successfully removed the log-out button which doesn't have any meaning to be on login page.
> Updated login page to remove log out button

- ncert.html
added class 8th books by exchanging dummy books in the NCERT section.
improved class 10th books.
Please check and merge.
> updating books of class 8th in NCERT section

- Quiz/css/style.css
- index.html
> Fix Responsiveness 

- assets/css/contact us.css
changed the contact us.css footer code added a proper code to align the footer at the bottom of the page
screenshot attached below
please mark it as hacktobefest will help me to reach my goal
before applying the code =>
after applying the code =>
> updated the css code for contact us footer was not aligned at bottom it was floating

- index.html
> Fixed footer section of index.html 

- assets/css/contact us.css
Fixes the issue with the footer and navbar of the contact us page, it is the same as other pages now.
Navbar before:-
Navbar after:-
Footer before:-
Footer after:-
Changes in the contact us page is done.
> Fixed footer and navbar of the contact us page

- blogs.html
> Added blog : Future Scope of Full Stack Developers in India

- index.html
This Issue closes Issue #1078 
I have corrected all the typos and some grammatical mistakes that I have found. Screenshot of some of the mistakes are below
If possilble please accept this as a Hacktoberfest PR
| Before      | After |
| ----------- | ----------- |
|   ![image](https://user-images.githubusercontent.com/92989288/197572029-c2fb3433-3a27-4f78-9450-b37b5dec1372.png) | ![image](https://user-images.githubusercontent.com/92989288/197572748-55eee305-ac6b-4704-aa02-fb964fe59950.png) |
|  ![image](https://user-images.githubusercontent.com/92989288/197573493-81bdbc5d-9fcb-4e67-9a41-91ef22706268.png) |![image](https://user-images.githubusercontent.com/92989288/197573751-9d5dd6c2-dad8-4d72-a50c-5a62607672c0.png)|
> Fixed Issue #1078 + Some Other Typos

- index.html
> Updated footer and added copyright code.

- index.html
Reverts SauravMukherjee44/Aec-Library-Website#1103
> Revert "Updated footer and added copyright code."

- assets/css/style.css
- index.html
Modal added Css 
Please do check it once . 
Waiting for your feedback (:.
Regards 
Shivam Urkude
> Changed the decorated the text of the project in Modal

- blogs.css
> Changing color of the cards in Blogs page #1087

- resource.html
In Resource Page Some Image are not visible for Web Dev, App Web, And Programming Section Due to Wrong Image Path. This PR Fixed all the issue related to Bug #1118 
https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/80810b1c-b0de-4b39-be38-aa06d1cc2c69
> Some Images are not visible #1118 Bug Resolved

- blogs.css
- blogs.html
- recommended_books.js
"I have improved the UI of blog page. I have customized the color of its cards and added a hover effect based on the website's theme.
Please add 'GSSoC'23' to the label.
> improved ui of blog page 

- assets/css/contributors.css
- contributors.html
> Improve footer responsiveness

- assets/css/style.css
Now Footer has it's right Position
I change property of footer styling. 
`postion:relative` to `postion: absolute`
> Footer Positioning #1136 Issue Fixed 

- assets/css/About.css
Blog Section Footer Element behaviour #1146 Fixed 
There are some Properties in Footer Which I fixed. 
https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/6d29b5f7-85b1-41a2-bb7d-4bc6a4704a8c
> Blog Section Footer Element behaviour #1146 Fixed

- index.html
Updated the nav-bar by making the nav-items open on a new tab, hence reducing the Loading Time of Website
> The  Nav-Items open on a new tab hence Reducing the Loading Time of Website

- assets/css/contributors.css
- assets/css/donate-book.css
- blogs.css
- blogs.html
- contributors.html
- public/donate-book.html
Closes #1154 
This issue was assigned to me.
- Added top-to-back button in the following pages : 
- Blogs        
- Contributors      
- Donate Books
> added back-to-top button

- assets/css/audiobook.css
- assets/css/style.css
- index.html
Please Closed: [#1162](https://github.com/SauravMukherjee44/Aec-Library-Website/issues/1162)
- Before: 
- After:
> Update Navbar UI

- assets/css/style.css
- index.html
Add JS validation in Issue_book form
> Improved issue form by added JS validation issue#1143 resolved

- about.html
- public/getabook.html
- [ X] My code follows the code style of this project.
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.
> added the get a book page

- README.md
Added a table of content as mentioned below to readme.md for easy navigation.
> Added a table of content to README.md

- .vscode/settings.json
- Quiz/css/style.css
- Quiz/js/game.js
- Quiz/pages/end.html
- Quiz/pages/game.html
- Quiz/pages/highscore.html
- index.html
> Quiz background changes

- resource.css
- resource.html
Footer of resource page need some improvement #1182 Fixed
In footer styling I changed the position style of footer element and the color when hover at footer element(icons). I checked for all the devices, my changes are working fine.
> Footer of resource page need some improvement #1182 Fixed

- CODE_OF_CONDUCT.md
- README.md
- about.html
- blogs.html
- index.html
- public/contact us .html
- public/privacy-policy.html
- public/terms&conditions.html
Correction of typos and grammatical errors
> Corrected typos and grammatical errors #1150

- Login_page/login.js
- Login_page/login_page.html
- Login_page/login_style.css
Changed the redirecting method after clicking the submit button and also playing the message Thankyou. Letting the user know he has successfully merged
- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.
https://github.com/SauravMukherjee44/Aec-Library-Website/assets/92723741/34723423-5ecc-4452-8073-7a18e4f9cdb5
> loginpage_fucntionality

- assets/css/style.css
- index.html
- recommended_books.js
I have changed the recommended books section of the website by adding some hover effects and box shadows.
Kindly inform me if you want any more changes.
> RECOMMEDED SECTION UPDATED

- assets/css/style.css
- index.html
- recommended_books.js
I have changed the audiobook section of the website by adding box-shadows and effects.
if you wanna any changes than kindly inform me.
> Audiobook section updated

- assets/css/style.css
Issue #1179 
-> Modified the design of scroll bar according to the color theme of the website.
> Modified scrollbar   (Issue -1179)

- Quiz/css/game.css
- Quiz/css/style.css
- Quiz/pages/end.html
- Quiz/pages/game.html
Feature: Improving readability/look of quiz/pages/game. {Gssoc'23} #1188
Screenshots are attached below.
If any other changes need to be made in this then, kindly mention it in the e-mail (srishti.sonam.11@gmail.com)
> Changes made on quick quiz made as mentioned

- assets/css/style.css
- index.html
This pull request fixes #1189  includes several CSS enhancements to improve the visual appearance and user experience of the website. The following changes have been made:
- Nav Link Hover Effect Fix: Fixed the hover effect on navigation links to ensure consistency and improve responsiveness.
- Borders in 'Your Books' Section: Added a bottom border to the 'Your Books' section to enhance visual separation and improve readability.
- Choose and Read Book Section Improvements: Made various enhancements to the 'Choose and Read Book' section, including improved layout, font modifications, and color adjustments to the book names according to the theme.
- Font Addition: Added the 'Baloo 2' cursive font to enhance the overall typography and give a unique touch to the website.
- Add Book Button …
> Nav Link Hover Effect, Borders, Font, Alignment, and Scrollbar Styling

- Contributors.md
- Login_page/style.css
- sign-up-page/index.html
- sign-up-page/style.css
**Solved: #1219 - Updated navigation icon and added responsiveness to the login and signup pages for all devices.** 
Before it look like this:
Login Page:
Signup page:
**After add the responsiveness it look like this:  issue solved #1219 @SauravMukherjee44 :**
[AEC liabary.webm](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/106610322/13078eed-c27a-446a-9482-0a8ab82612c0)
> Solved: #1219 - Updated navigation icon and added responsiveness to the login and signup pages for all devices.

- assets/css/style.css
- index.html
Addition of links to the FAQ section that navigate to the respective sections.
> Addition of section links to Faq section

- about.html
- assets/css/About.css
- assets/css/donate-book.css
- assets/css/style.css
- index.html
- public/donate-book.html
- recommended_books.js
> Formatting the datatable in home page and enhancing the readability by changing the css

- resource.css
AEC-Library Tag in Resource Page #1220 fixed
There were some Styling issue in resources.css which I have changed.
> AEC-Library Tag in Resource Page #1220 fixed

- resource.css
- resource.html
Feature: Changing Hover effect on button #1211
Added more interactive hover effect on the buttons in Resource section
Before
https://github.com/SauravMukherjee44/Aec-Library-Website/assets/127978268/8ddd19cf-939a-4ddc-8119-4c19db263028
After Changes
https://github.com/SauravMukherjee44/Aec-Library-Website/assets/127978268/b530336b-6d04-403b-8814-3504ab676197
> hover effect added 

- blogs.css
Blog card Enhancement #1294 Fixed
https://github.com/SauravMukherjee44/Aec-Library-Website/assets/99237795/5d5fe0ff-db94-4a4f-8b38-5da75c621bd4
> Blog card Enhancement #1294 Fixed

- resource.css
- resource.html
> Made resources page responsive

- assets/css/style.css
Read Book button issue #1260 Fixed
In .search-heading we need to give padding 2px 12px
> Read Book button issue #1260 Fixed

- blogs.css
Closes #1249 
Make the 'Blogs' page responsive
-  My code follows the code style of this project.
-  This PR does not contain plagiarized content.
-  The title of my pull request is a short description of the requested changes.
https://github.com/SauravMukherjee44/Aec-Library-Website/assets/112184998/caea2fa9-bd0f-4ecb-ac29-e6a7aa9f1b4e
> Made 'Blogs' page responsive

- assets/css/style.css
- index.html
FAQ button directing to the FAQ section is added to the navbar in the homepage.
Screenshots of the changes were attached here.
Pervious one
> FAQ added to Navbar

- .vscode/settings.json
- about.html
- assets/css/faq.css
- public/faq.html
#1239 
Added FAQ section separately and linked the FAQ button in the about page.
Please see the screenshot of the changes made.
> #issue 1239 Faq section added

- Login_page/login_page.html
- sign-up-page/index.html
- sign-up-page/style.css
#1379
Validation add for all empty fields
Add red bottom border for empty field
Add green bottom border for correct input
Error message shown in top
@rohanbabbar04  Please check it !! issue#1379 resolved
> Add validation in Signup and Signin form

- assets/css/donate-book.css
- public/donate-book.html
#1207
Validations added on book donation form
1)Empty field validation on input fields and dropdown menus
2)Email validation add
3)contact no should be 10 digits
4)Default landmark and contact made required inputs
5)Error message shown below of each fields
@rohanbabbar04 Please review it!!
> Validation added on Book Donation Form issue#1207 resolved

- public/contact us .html
Fixes #1384 
Changes proposed
I added the form tag which was the main part of the validations in the contact us form. 
I also changed the type of the phone number and email to their appropriate types so that only those values can be added for better usability.
> #1384 : Updated contact us .html file by adding form validations 

- public/contact us .html
- resource.css
- resource.html
#1404 
Contact Us at the bottom of the resources page appeared twice. It was corrected.
the resources page before correction
resources page after correction
mobile view
> # 1404 Footer setion edited

- Login_page/login_page.html
Fix-bug: password not displayed when clicking the eye button while adding a password #1421
Click on the eye button next to the password input field to reveal the password.
- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.
> Bug_fix: Added changes in login_page.html for updating eyebutton feature

- index.html
Closes #1420
- [x ] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.
> Added Aria label on socials

- about.html
- public/contact us .html
- resource.html
Hey @SauravMukherjee44 ,
This PR solves issue #1212 - I made email addresses clickable so that when you click on the email address a new email window opens with the recipient's address already filled in. The user only needs to type the body of the email. 
This PR solves issue #1270 - Corrected grammatical error in about.html
This PR solves issue #1271 - Added course image in resource.html
Issue #1212 demo after solving
https://github.com/SauravMukherjee44/Aec-Library-Website/assets/106817047/4c291c72-10ab-4314-ad98-ac6128758055
> Fixes issue #1212, #1270 and #1271

- public/privacy-policy.html
I have added the email tag to the privacy-policy.html file, inside the contact us section. 
It provides an option to specify an email address to send an email.
> Added the email tag in privacy-policy.html file 

- resource.css
> Added Hover effect to Resources social icons

- about.html
- blogs.html
- cbse_notes.html
- contributors.html
- index.html
- ncert.html
- resource.html
- reviewsection.html
- **This PR is linked to Old PR #1253 . Because of, Some conflict Issues Placed in My Local Project Directory**
- **Modified and Added Semantic Tags `<header>, <main>, <section>` in `contributors.html, about.html, blogs.html, cbse_notes.html, index.html, ncert.html, resource.html, reviewsection.html` Files.**
- **In Some Files Remove `<center></center> ` Tag**
- **`For Reviewers, Observe My Changes in Files Changed File`**
- **This PR is linked to Old PR #1253 . Because of, Some conflict Issues Placed in My Local Project Directory of Old PR. Atleast this PR raised 2 months ago**
- **Please taken my Requests into Consideration. Take review on this. If applicable, Merge this ?**
> fix: Fixed Semantic changes in Multiple HTML Files

- Login_page/login_page.html
- public/contact us .html
- sign-up-page/index.html
Closes #1445 
Added aria attributes like aria-required, aria-describedby, aria-label, role to Login, Sign up, and Contact Us form present in the project.
> Added aria attributes to all forms

- Quiz/css/style.css
- Quiz/pages/highscore.html
- Quiz/pages/quizhome.html
- assets/css/style.css
- index.html
closes#1471
- Added a link to Quiz page in the navigation bar through "Play Quiz".
- Created a Quiz page which is linked to "Play Quiz".
- Removed the quiz section from home page as now it can be accessed through navigation bar.
- Added some styling for the created page.
> Quiz page added in header.
